In [0]:
'''Initialize and print two arrays 𝑐 and 𝑑 having the following properties:

    𝑐 is a row vector with all non-negative integer values less than 100
    𝑑 is a square matrix of size 3 having all entries as 0.0
'''

import numpy as np
c=np.arange(100)
print(c)
z=np.empty([3,3])
z.fill(0)
print(z)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
#Import numpy with an alias name np. Initialize two arrays 𝑎, 𝑏 of size 3×5 with random values and print them. 
a=np.empty([3,5])
b=np.empty([3,5])
print(a)
print(b)

[[1.0006086e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000]]
[[1.00061495e-316 1.01855798e-312 1.01855798e-312 9.54898106e-313
  1.14587773e-312]
 [1.03977794e-312 1.23075756e-312 1.03977794e-312 1.10343781e-312
  9.76118064e-313]
 [1.18831764e-312 1.01855798e-312 1.01855798e-312 2.22809558e-312
  2.14321575e-312]]


In [0]:
#We have 𝑒 as following : e = [[1,2,3],[4,5,6],[7,8,9]]. Change 𝑒 as a numpy array and print it.

e = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(e)
print(e)
print(arr)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
#𝑓 and 𝑔 are two square matrices of size 5 such that all the entries of 𝑓 are 1 and 𝑔 is an identity matrix. Initialize them and print them
f=np.empty([5,5])
f.fill(1)
print(f)
I=np.identity(5)
print(I)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [0]:
#Reshape 𝑐 into a 10×10 matrix and name it ℎ. Now flatten ℎ, call it 𝑐′ and print YES when the shapes of 𝑐 and 𝑐′ are same. Otherwise print 
print(c)
h=c.reshape([10,10])
print(h)
cf=h.flatten()
print(cf)
if c.shape == h.shape:
  print("YES")
else:
  print("NO")


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
NO


In [0]:
#Let 𝐴 denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose 𝐴, call it 𝐴′, such that its shape is (5,2,10) and print it.
A = np.random.rand(2,10,5)
print(A)
AT = A.transpose(2,0,1)
print(AT)

[[[0.48046036 0.28893974 0.69152767 0.90798948 0.56917926]
  [0.49768028 0.60235608 0.25688676 0.26969505 0.06601287]
  [0.8444161  0.64068633 0.37868855 0.03886554 0.28389505]
  [0.61280962 0.99377697 0.9065779  0.73075844 0.51288635]
  [0.91581089 0.64649929 0.24384585 0.55281895 0.76809485]
  [0.46750566 0.70873342 0.82264359 0.48216479 0.54656205]
  [0.55168496 0.2922896  0.05389838 0.59021392 0.86179284]
  [0.18363359 0.71059832 0.82011933 0.47620266 0.34404063]
  [0.32173943 0.24493694 0.042996   0.0941364  0.51623426]
  [0.26048645 0.00678314 0.37097267 0.3539766  0.55044836]]

 [[0.59304079 0.42462719 0.15274773 0.11854214 0.13083263]
  [0.49363163 0.72538668 0.08781411 0.65931883 0.71423081]
  [0.3018021  0.44187596 0.83359523 0.26907257 0.79861167]
  [0.70326723 0.50334076 0.1566791  0.81807134 0.81258659]
  [0.4073294  0.82081545 0.75666989 0.16459523 0.85132913]
  [0.45637467 0.29591319 0.48133977 0.9585484  0.15549972]
  [0.23413112 0.1566193  0.77463691 0.61183619 0.61239

In [0]:
'''
You have a matrix 𝑋 of size (10,5) filled with random values. Print the following :

    Minimum value and index where it occured, for each column
    Maximum value and the index where it occured, for each column
    Minimum value and index where it occured, for each row
    Maximum value and index where it occured, for each row
    Minimum value and index where it occured, for the entire matrix
    Maximum value and index where it occured, for the entire matrix
'''
X = np.empty([10,5])

print(np.argmin(X,axis=0))
print(np.argmax(X,axis=0))
print(np.argmin(X,axis=1))
print(np.argmax(X,axis=1))
print(np.amin(X))
print(np.amax(X))
print(X)






[0 1 0 0 5]
[7 7 7 8 7]
[3 1 2 3 0 4 3 3 4 2]
[4 3 1 2 3 0 2 2 3 1]
0.0
8.496307828983975e+136
[[2.01801232e-316 1.35710504e-153 1.35827041e-153 0.00000000e+000
  3.00735176e-067]
 [5.54760571e-048 0.00000000e+000 1.96805123e-062 3.63042743e-043
  1.04857803e-142]
 [8.57631745e-043 1.03699796e-042 4.56342110e-072 1.13907626e-071
  1.36546825e-071]
 [1.65019454e-153 1.65602137e-153 1.65718674e-153 1.20771395e-153
  1.20887932e-153]
 [1.21004469e-153 4.58663944e-072 8.46088825e-053 1.56076428e-033
  4.02473852e-066]
 [7.42433215e-047 1.81816158e-321 1.89242145e-052 2.31004096e-052
  0.00000000e+000]
 [1.81152938e-152 1.81152938e-152 1.16096346e-028 1.50656320e-153
  1.50772857e-153]
 [1.16467185e-028 8.49629008e+136 8.49630783e+136 6.04114745e-154
  1.29040557e-057]
 [2.38038710e-038 1.55286349e-033 3.87609918e-033 4.64647120e-033
  4.16304307e-062]
 [5.13538927e-062 6.10773546e-062 1.80431417e-153 1.80547953e-153
  1.80664490e-153]]


In [0]:
np.random.seed(0)
X = np.random.rand(10,5)
'''
Find and print the following for the matrix X:

    Mean of each row and column
    Standard deviation of each row and column
    Mean of the entire matrix
    Standard deviation of entire matrix

'''
print(np.mean(X,axis=0))
print(np.mean(X,axis=1))
print(np.std(X,axis=0))
print(np.std(X,axis=1))
print(np.mean(X))
print(np.std(X))

[0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
[0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
[0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
0.5379651182755409
0.27226582292177587


In [0]:
'''
Let 𝑌 denote a square matrix of size 10 with random values. Print the following:

    Determinant
    Rank of the matrix
    Diagonal Elements
    Trace
    Eigen values
    Matrices obtained after Singular Value Decomposition
    Inverse if exists, otherwise Pseudo-Inverse
    Multiplication 𝑌 with 𝑋
    Element-wise multiplication of 𝑌 and its inverse(or pseudo-inverse)
'''

np.random.seed(3)
Y = np.random.rand(10,10)

print(np.linalg.det(Y))
print(np.linalg.matrix_rank(Y))
print(np.diagonal(Y))
print(np.trace(Y))
print(np.linalg.eigvals(Y))
u, s, vh = np.linalg.svd(Y, full_matrices=True)
print(u.shape, s.shape, vh.shape)
print(u,s,vh)
print("Inverse")
print(np.linalg.inv(Y))


-0.012807808169095483
10
[0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]
4.497309545724899
[ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j]
(10, 10) (10,) (10, 10)
[[-0.31776408 -0.02455508 -0.60644878 -0.17883359 -0.12672161  0.14873878
  -0.17823942 -0.52859453 -0.02295855 -0.38570883]
 [-0.26118514 -0.10864541 -0.24911354  0.26547359  0.52168399 -0.25773901
  -0.46995326  0.21752636 -0.39285046  0.16234491]
 [-0.31347907 -0.34483471 -0.25292297  0.1214296   0.1486964   0.33436315
   0.54080229  0.48017168  0.05660692 -0.20966421]
 [-0.35815379  0.59490017  0.30255161  0.15850614 -0.11046295  0.3051409
   0.07395537  0.03044889 -0.50561658 -0.18384856]
 [-0.28385845 -0.18085696 -0.1583078   0.10535533 -0.46807835 -0.08377643
   0.24075

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv Read the data and display the first 5 rows
#file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"

dt = pd.read_csv("http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv")
print(dt.head())
#Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame
dt.fillna(dt.mean())
titanic_data_new=pd.get_dummies(dt, columns=['sex', 'embarked','pclass'])
titanic_data_new.head()
len(titanic_data_new.columns)

titanic_data_new.drop(df.iloc[:, 1:3], inplace = True, axis = 1) 




   pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]


19